### ISSUE TITLE
Bug: ledgerblue.commException.CommException: Exception : No dongle found

### ISSUE THREAD

**Issue by usmanovbf** [ton-blockchain/ledger-app-ton#4]
Hi! 
I am trying to execute `make load` against my Ledger Nano X and have faced the error:
```
(base) ➜  ledger-app-ton git:(master) ✗ ./env.sh
bash-5.1# make load
BOLOS_ENV is not set: falling back to CLANGPATH and GCCPATH
CLANGPATH is not set: clang will be used from PATH
GCCPATH is not set: arm-none-eabi-* will be used from PATH
[CP] build/nanos2/bin/app.elf => bin/app.elf
[CP] build/nanos2/bin/app.hex => bin/app.hex
[CP] build/nanos2/dbg/app.map => debug/app.map
[CP] build/nanos2/bin/app.apdu => bin/app.apdu
[CP] build/nanos2/bin/app.sha256 => bin/app.sha256
[CP] build/nanos2/dbg/app.asm => debug/app.asm
python3 -m ledgerblue.loadApp --curve ed25519 --appFlags 0x000 --path "44'/607'" --tlv --targetId 0x33100004 --targetVersion="" --apiLevel 1 --delete --fileName bin/app.hex --appName "TON" --appVersion "1.2.0" --dataSize $((0x`cat debug/app.map |grep _envram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'` - 0x`cat debug/app.map |grep _nvram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'`)) `ICONHEX=\`python3 /opt/nanosplus-secure-sdk/icon3.py --hexbitmaponly icons/nanox_app_ton.gif  2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"`  --tlvraw 9F:01
Generated random root public key : b'04c92eeab8566342ad92761add676358cd057ddec54d4e1d7ad4066ca000266bf106891f6bca931dc115058573199ab73580983d8ed2f23a83fec7f861245c1406'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/ledgerblue/loadApp.py", line 171, in <module>
    dongle = getDongle(args.apdu)
  File "/usr/lib/python3.9/site-packages/ledgerblue/comm.py", line 385, in getDongle
    raise CommException("No dongle found")
ledgerblue.commException.CommException: Exception : No dongle found
make: *** [Makefile:122: load] Error 1
```

My env:
* macOs
* Darwin laptop-name 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
* Docker version 20.10.12, build e91ed57

How can I fix the error and identify my Ledger?

**Comment by ex3ndr** [comment]
You need to forward your usb dongle correctly, try to edit env.sh and use correct usb device id

**Comment by usmanovbf** [comment]
> You need to forward your usb dongle correctly, try to edit env.sh and use correct usb device id

@ex3ndr Thanks for your advice, but, seems, it doesn't help because it's not possible to access the USB devices on macOS due to underlying restrictions, see https://stackoverflow.com/a/68629163 and https://github.com/moby/hyperkit/issues/149

yeah, I tried to change the BOLOS_SDK variable in the ./env.sh to BOLOS_SDK=/opt/nanox-secure-sdk but it doesn't help due to the aforementioned reason.


Closed without a solution for macOS. The only workaround is to switch to Ubuntu Linux simply

**Comment by ex3ndr** [comment]
Yes, it is not possible on mac, i am using dedicated linux laptop for development and develop remotely using vs code
